/**
 * style-library.ts — the visual STYLE LIBRARY + selector for B-roll generation.
 *
 * A categorized catalog of visual styles, each with a DESCRIPTION (what it evokes), a
 * whenToUse fit-signal, and the Kling-effective KEYWORDS fragment. The prompt-engineer /
 * selector reads the descriptions to pick the best-fit style for a video, then injects
 * the keywords. Style is chosen ONCE per video for consistency (matched to the reference),
 * with an optional grade MODIFIER layered on. Keywords + reliability sourced from 2026
 * Kling/Sora prompt research (fal.ai, klingaio, videoai.me, MagicHour, ZSky, et al.).
 *
 * reliability = how dependably Kling renders the look: realistic/cinematic/3D = high;
 * flat-2D / dense-text / painterly = low (need rerolls / do in MoGraph instead).
 *
 * This is also the Phase-2 visual-KB seam: tagged KB exemplars become entries here.
 */

export type StyleCategory =
  | "realistic" | "cinematic" | "photographic"
  | "animation_3d" | "illustration_2d" | "motion_graphic"
  | "retro_era" | "artistic_medium" | "mood_grade";

export type StyleReliability = "high" | "medium" | "low";

export interface VisualStyle {
  id: string;
  name: string;
  category: StyleCategory;
  /** "style" = a full base look; "modifier" = a grade/mood that LAYERS on a base */
  kind: "style" | "modifier";
  description: string; // what it is + what it evokes
  whenToUse: string;   // the selection signal the selector reads
  keywords: string;    // the Kling-effective prompt fragment
  reliability: StyleReliability;
}

export const STYLE_LIBRARY: VisualStyle[] = [
  // ── REALISTIC ──
  { id: "documentary_verite", name: "Observational Vérité Documentary", category: "realistic", kind: "style", reliability: "high", description: "Fly-on-the-wall unstaged footage that feels captured, not composed.", whenToUse: "Authentic human moments, interviews, behind-the-scenes where polish reads as fake.", keywords: "observational documentary, handheld shoulder-mounted camera, available natural light, imperfect framing, candid unstaged moment, subtle micro-shake, naturalistic, light film grain, no color grade" },
  { id: "photojournalistic", name: "Photojournalistic / Reportage", category: "realistic", kind: "style", reliability: "high", description: "On-the-ground reportage with decisive framing and existing-light realism.", whenToUse: "Gritty real-world scenes, social/cause stories, anything needing journalistic credibility.", keywords: "photojournalistic reportage, available light, candid decisive moment, 35mm prime lens, neutral color, gritty realism, slight motion blur, documentary framing, photorealistic skin texture" },
  { id: "naturalistic_handheld", name: "Naturalistic Handheld", category: "realistic", kind: "style", reliability: "high", description: "Camera that breathes with the subject — gentle handheld, motivated light, intimate.", whenToUse: "Emotional talking-head, intimate dialogue, lifestyle where the camera should feel human.", keywords: "naturalistic handheld, gentle camera breathing, motivated practical light, soft window light, intimate framing, shallow natural depth of field, realistic skin, subtle grain, lived-in textures" },
  { id: "ugc_iphone_real", name: "UGC / iPhone Real", category: "realistic", kind: "style", reliability: "high", description: "Looks shot on a modern phone and posted straight to TikTok — imperfect, very now.", whenToUse: "Creator/social ads, testimonials, 'real person' UGC where studio polish kills trust.", keywords: "shot on iPhone, UGC selfie style, phone-camera sharpness, slight digital noise, natural everyday lighting, handheld micro-shake, imperfect casual framing, vertical social video, unfiltered realistic" },
  { id: "naturalistic_available_light", name: "Available-Light Realism", category: "realistic", kind: "style", reliability: "high", description: "Clean restrained realism lit only by real sources — true color, no cinematic push.", whenToUse: "Product-in-use, real interiors, honest demos that must read as ordinary reality.", keywords: "naturalistic available light, true-to-life color, soft daylight from window, neutral white balance, realistic textures, natural imperfections, fine subtle grain, photorealistic, restrained contrast" },

  // ── CINEMATIC ──
  { id: "cinematic_film_look", name: "Cinematic Film Look", category: "cinematic", kind: "style", reliability: "high", description: "The 'looks like a movie' baseline — controlled light, filmic contrast, shallow depth, gentle grain.", whenToUse: "Default premium upgrade for any B-roll without committing to an era or palette.", keywords: "cinematic film still, 35mm film grain, shallow depth of field, soft key light with rim, filmic contrast, motivated lighting, subtle color grade, high production value" },
  { id: "cinematic_anamorphic", name: "Anamorphic Widescreen", category: "cinematic", kind: "style", reliability: "high", description: "Scope-format look with horizontal flares and oval bokeh — epic blockbuster.", whenToUse: "Sweeping establishers, hero reveals, automotive/landscape, large-scale theatrical shots.", keywords: "anamorphic 2.39:1 widescreen, horizontal blue lens flare, oval bokeh, lens breathing, edge distortion, shallow depth of field, cinematic, 35mm, soft highlight roll-off" },
  { id: "teal_orange_blockbuster", name: "Teal-and-Orange Blockbuster", category: "cinematic", kind: "style", reliability: "high", description: "Hollywood grade splitting cool teal shadows against warm skin for subject pop.", whenToUse: "Action, trailers, energetic promos, fitness/automotive — high-budget commercial feel.", keywords: "teal and orange color grade, split toning, cool teal shadows, warm orange skin tones, complementary contrast, cinematic blockbuster, shallow depth of field, high dynamic range" },
  { id: "deakins_naturalistic", name: "Deakins Naturalistic", category: "cinematic", kind: "style", reliability: "high", description: "Restrained motivated single-source light with clean negative space — cinematic, never showy.", whenToUse: "Prestige interviews, thoughtful narrative, premium-but-understated brand work.", keywords: "naturalistic motivated lighting, single soft key source, practical light, restrained color, deep shadows, clean negative space, large-format look, subtle contrast, photoreal, minimal grade" },
  { id: "a24_indie", name: "A24 Indie", category: "cinematic", kind: "style", reliability: "high", description: "Soft golden glow, muted palette, grainy 'like-a-memory' texture, intimate handheld.", whenToUse: "Emotional character-driven, nostalgic or melancholic stories; artful lifestyle.", keywords: "A24 indie film look, soft golden hour glow, muted desaturated palette, intimate handheld framing, motivated practical light, 35mm film grain, lived-in texture, nostalgic mood" },
  { id: "film_noir", name: "Classic Film Noir", category: "cinematic", kind: "style", reliability: "medium", description: "High-contrast B&W with hard chiaroscuro shadows and moody fatalism.", whenToUse: "Mystery, suspense, dramatic monologue, stylized crime/period mood.", keywords: "film noir, black and white, high contrast chiaroscuro, hard low-key lighting, deep crushed blacks, venetian blind shadows, smoky atmosphere, dramatic silhouettes, vintage 35mm grain" },
  { id: "neon_neo_noir", name: "Neon Neo-Noir", category: "cinematic", kind: "style", reliability: "high", description: "Rain-slicked night city in magenta and cyan neon — modern cyberpunk-adjacent noir.", whenToUse: "Night urban, music-video energy, edgy tech/product launches, after-dark moods.", keywords: "neo-noir neon, magenta and cyan neon signs, wet reflective pavement, rim lighting, low-key moody, anamorphic flare, volumetric haze, desaturated teal grade, night city, crushed blacks" },
  { id: "golden_hour_cinematic", name: "Golden-Hour Cinematic", category: "cinematic", kind: "style", reliability: "high", description: "Warm low sun, long shadows, glowing backlight and hazy bloom — romantic, aspirational.", whenToUse: "Lifestyle, travel, wellness, hopeful brand stories, outdoor hero shots.", keywords: "golden hour, warm low-angle sunlight, long soft shadows, glowing backlight rim, gentle lens haze, warm amber grade, shallow depth of field, cinematic, soft highlight bloom" },

  // ── PHOTOGRAPHIC ──
  { id: "film_35mm_grain", name: "35mm Film Grain", category: "photographic", kind: "style", reliability: "high", description: "Organic analog texture — fine grain, gate weave, soft halation — grounds footage as physically shot.", whenToUse: "Any clip that feels too clean/CGI; a quick credibility-and-warmth pass.", keywords: "shot on 35mm film, fine organic film grain, subtle halation, soft gate weave, photochemical contrast, gentle highlight roll-off, analog texture, slight chromatic aberration, filmic color" },
  { id: "kodak_portra_warm", name: "Kodak Portra Warm", category: "photographic", kind: "style", reliability: "high", description: "Soft pastel-and-earth palette with creamy skin tones and fine grain — gentle nostalgic stock.", whenToUse: "People-focused, lifestyle, beauty, intimate portraits needing flattering skin.", keywords: "Kodak Portra 400, warm soft pastel tones, creamy natural skin tones, fine grain, soft natural lighting, shallow depth of field, gentle earth-tone palette, nostalgic warmth, 35mm" },
  { id: "shallow_dof_portrait", name: "Shallow-DOF Bokeh Portrait", category: "photographic", kind: "style", reliability: "high", description: "Fast-prime portrait — subject razor-sharp, background melting into creamy bokeh.", whenToUse: "Talking-head close-ups, product hero shots, strong subject isolation.", keywords: "85mm f/1.4 portrait lens, extremely shallow depth of field, creamy circular bokeh, subject in sharp focus, soft blurred background, background lights bokeh, gentle rim light, photoreal skin" },
  { id: "wide_angle_environmental", name: "Wide-Angle Environmental", category: "photographic", kind: "style", reliability: "high", description: "Wide field placing the subject in a deep detailed environment, front-to-back sharp.", whenToUse: "Establishers, place-driven stories, architecture/landscape/travel, subject in context.", keywords: "wide-angle 24mm lens, deep focus, expansive environmental framing, foreground depth, sweeping landscape, natural daylight, high detail throughout, subject in context" },
  { id: "macro_detail", name: "Macro Detail", category: "photographic", kind: "style", reliability: "high", description: "Extreme close-up of fine texture with razor-thin focus and creamy fall-off.", whenToUse: "Product texture, food, materials, satisfying tactile B-roll inserts.", keywords: "extreme macro close-up, fine surface texture, razor-thin depth of field, creamy bokeh fall-off, studio side-lighting, crisp focus on detail, tactile realism, slow dolly-in" },
  { id: "high_key_bright", name: "High-Key Bright", category: "photographic", kind: "style", reliability: "high", description: "Bright airy near-shadowless light, clean palette — fresh, optimistic, commercial.", whenToUse: "Clean product/beauty, tech, wellness, upbeat social ads — positive and trustworthy.", keywords: "high-key lighting, bright airy, soft shadowless light, clean white background, even soft fill, vibrant fresh palette, crisp clarity, commercial studio look, light and optimistic" },
  { id: "low_key_moody", name: "Low-Key Moody", category: "photographic", kind: "style", reliability: "high", description: "Dark dramatic single-source light, deep shadows, sliver of highlight — tense, premium.", whenToUse: "Dramatic reveals, luxury/spirits/automotive, suspense, premium moody brand work.", keywords: "low-key lighting, single hard source, deep dramatic shadows, chiaroscuro, dark moody atmosphere, strong rim light, crushed blacks, selective highlight, volumetric haze" },

  // ── ANIMATION 3D ──
  { id: "pixar_3d", name: "Pixar-Style 3D", category: "animation_3d", kind: "style", reliability: "high", description: "Glossy big-eyed character CGI with soft GI and rounded appealing forms.", whenToUse: "Charming character explainers, mascots, feel-good emotional beats for broad audiences.", keywords: "Pixar-style 3D animation, stylized 3D character, subsurface scattering skin, soft global illumination, big expressive eyes, rounded appealing design, cinematic depth of field, warm bounce light, polished CGI render, family-friendly" },
  { id: "dreamworks_3d", name: "DreamWorks 3D", category: "animation_3d", kind: "style", reliability: "high", description: "High-energy stylized CGI with sharper features and punchy cinematic light.", whenToUse: "Dynamic action, comedic timing, adventurous hero moments needing edge.", keywords: "DreamWorks-style 3D animation, stylized cartoon CGI, exaggerated facial expression, dynamic action pose, sharp character features, dramatic rim lighting, vibrant cinematic color, glossy 3D render, energetic motion" },
  { id: "unreal_game_cinematic", name: "Stylized Game Cinematic", category: "animation_3d", kind: "style", reliability: "high", description: "Real-time-engine cinematic with PBR materials and volumetric light — AAA cutscene.", whenToUse: "Sci-fi/fantasy hero shots, tech reveals, high-drama cinematic sequences.", keywords: "Unreal Engine cinematic, real-time 3D render, physically based materials, volumetric lighting, ray-traced reflections, game cutscene aesthetic, dramatic camera move, high detail environment, AAA game trailer" },
  { id: "claymation_stopmotion", name: "Claymation / Stop-Motion", category: "animation_3d", kind: "style", reliability: "medium", description: "Handmade clay-puppet look with fingerprints, tactile texture, deliberate judder.", whenToUse: "Quirky handmade nostalgic stories, whimsical brand pieces.", keywords: "claymation, stop-motion animation, polymer clay texture, visible fingerprints, handmade miniature set, Aardman style, 12fps stop-motion judder, practical studio lighting, tilt-shift" },
  { id: "blender_product_3d", name: "Blender 3D Product Render", category: "animation_3d", kind: "style", reliability: "high", description: "Clean studio-lit product CGI with crisp materials and smooth turntable motion.", whenToUse: "Product reveals, packaging hero shots, minimalist commercial loops.", keywords: "3D product render, studio lighting, seamless gradient backdrop, smooth turntable rotation, physically based materials, soft reflections, macro detail, clean commercial render, glossy surfaces, shallow depth of field" },
  { id: "low_poly_3d", name: "Low-Poly 3D", category: "animation_3d", kind: "style", reliability: "medium", description: "Faceted geometric 3D with flat-shaded triangles — clean modern indie-game look.", whenToUse: "Abstract concept explainers, journeys/processes, stylized tech visuals.", keywords: "low poly 3D, faceted geometry, flat-shaded polygons, minimalist 3D world, simple geometric shapes, soft ambient occlusion, pastel color palette, isometric low-poly scene, clean studio lighting" },
  { id: "tilt_shift_miniature", name: "Miniature / Tilt-Shift", category: "animation_3d", kind: "style", reliability: "high", description: "Macro tilt-shift that shrinks real scenes into toy-like dioramas.", whenToUse: "Cute overhead city/crowd scenes, 'tiny world' transitions, playful establishers.", keywords: "tilt-shift miniature, toy model world, diorama scene, macro photography, exaggerated shallow focus, high angle overhead, saturated toy colors, miniature people, narrow focus band" },

  // ── ILLUSTRATION 2D (mostly LOW reliability on AI video — drift/warps) ──
  { id: "cel_shaded_anime", name: "Cel-Shaded Anime", category: "illustration_2d", kind: "style", reliability: "low", description: "Hard-edged 2D anime with bold outlines, flat cel shading, saturated color.", whenToUse: "Stylized action, youthful energetic narration, emotive anime-trope moments.", keywords: "cel-shaded anime, anime style, bold black outlines, flat cel shading, vibrant saturated colors, detailed expressive eyes, dynamic action pose, speed lines, 2D anime aesthetic" },
  { id: "studio_ghibli", name: "Studio-Ghibli Style", category: "illustration_2d", kind: "style", reliability: "medium", description: "Soft hand-painted 2D with lush watercolor backgrounds — nostalgic, nature-filled wonder.", whenToUse: "Calm emotional nature-themed storytelling, gentle dreamlike moods.", keywords: "Studio Ghibli inspired, hand-painted 2D animation, soft watercolor backgrounds, lush nature scenery, gentle character outlines, warm nostalgic palette, painterly clouds, soft diffuse light, dreamy mood" },
  { id: "comic_graphic_novel", name: "Comic / Graphic Novel", category: "illustration_2d", kind: "style", reliability: "low", description: "Inked comic look with bold linework, halftone shading, dramatic high-contrast color.", whenToUse: "Punchy hero reveals, dramatic narration, bold stylized printed-page action.", keywords: "graphic novel style, comic book illustration, bold ink outlines, halftone dot shading, dramatic high contrast, cross-hatching, saturated flat colors, dynamic action panel, hand-inked aesthetic" },
  { id: "flat_vector_illustration", name: "Flat Vector Illustration", category: "illustration_2d", kind: "style", reliability: "low", description: "Clean corporate 2D with flat fills and simple geometric characters.", whenToUse: "SaaS/corporate explainers, app walkthroughs, on-brand concept animation.", keywords: "flat vector illustration, corporate flat design, simple geometric characters, flat color fills, minimal shading, clean line shapes, bright brand palette, 2D explainer style, negative space" },
  { id: "hand_drawn_sketch", name: "Hand-Drawn Sketch", category: "illustration_2d", kind: "style", reliability: "low", description: "Loose pencil/ink sketch with visible strokes — raw artist's-notebook spontaneity.", whenToUse: "Creative/artsy intros, brainstorm visuals, warm human-made textures.", keywords: "hand-drawn sketch, pencil illustration, visible sketch strokes, rough linework, cross-hatch shading, ink on paper texture, monochrome sketch, loose gestural drawing, sketchbook aesthetic" },
  { id: "watercolor_2d", name: "Watercolor 2D Animation", category: "illustration_2d", kind: "style", reliability: "medium", description: "Soft pigment-on-paper with bleeding washes and visible grain — storybook gentleness.", whenToUse: "Tender emotional pieces, nature/wellness themes, elegant artisanal moods.", keywords: "watercolor animation, soft pigment washes, bleeding color edges, visible paper texture, delicate brushstrokes, pastel palette, wet-on-wet blending, hand-painted illustration, gentle organic motion" },
  { id: "paper_cutout_collage", name: "Paper-Cutout Collage", category: "illustration_2d", kind: "style", reliability: "medium", description: "Layered cut-paper with visible edges, drop shadows, stop-motion movement.", whenToUse: "Playful kids' content, craft/DIY brands, quirky layered transitions.", keywords: "paper cutout animation, layered cut paper, visible paper edges, soft drop shadows, construction paper texture, collage style, handmade craft aesthetic, flat layered depth, stop-motion paper movement" },
  { id: "storybook_illustration", name: "Storybook Illustration", category: "illustration_2d", kind: "style", reliability: "medium", description: "Warm children's-book art with painterly textures and cozy palettes.", whenToUse: "Narrated fables, kids' education, warm whimsical brand stories.", keywords: "children's storybook illustration, painterly picture-book style, warm cozy palette, soft textured shading, whimsical friendly characters, gouache texture, gentle rounded shapes, fairytale mood" },

  // ── MOTION GRAPHIC (text-heavy = LOW; do in Remotion/AE instead) ──
  { id: "kinetic_typography", name: "Kinetic Typography", category: "motion_graphic", kind: "style", reliability: "low", description: "Animated text that scales and reveals in rhythm — punchy message-forward motion.", whenToUse: "Short quote/CTA hits, single-phrase title cards (keep to 1–3 large words).", keywords: "kinetic typography, animated bold text, word-by-word reveal, large legible headline, high contrast lettering, rhythmic scale animation, clean sans-serif, minimal background, single short phrase" },
  { id: "flat_motion_graphics", name: "Flat Motion Graphics", category: "motion_graphic", kind: "style", reliability: "low", description: "Animated flat shapes and icons with smooth easing — crisp modern explainer design.", whenToUse: "Data/concept explainers, brand transitions, abstract loops with no characters.", keywords: "flat motion graphics, animated geometric shapes, smooth shape morphing, clean icon animation, bold flat colors, minimal vector style, easing transitions, modern design system, 2D motion design" },
  { id: "isometric_infographic", name: "Isometric Infographic", category: "motion_graphic", kind: "style", reliability: "medium", description: "Orthographic isometric diagrams with tidy structures — clean technical clarity.", whenToUse: "Tech/infrastructure explainers, workflows, 'how a system works' diagrams.", keywords: "isometric 3D infographic, orthographic projection, low-poly isometric scene, clean technical diagram, animated data flow, tidy geometric structures, pastel tech palette, soft ambient occlusion" },
  { id: "whiteboard_doodle", name: "Whiteboard / Doodle", category: "motion_graphic", kind: "style", reliability: "low", description: "Black-marker line drawings appearing on white in a hand-drawn reveal.", whenToUse: "Educational walkthroughs, process explainers, simple instructional storytelling.", keywords: "whiteboard animation, hand-drawn doodle, black marker line art, white background, draw-on reveal, simple stick figures, minimal sketch icons, educational explainer, sequential drawing" },
  { id: "neon_line_art", name: "Neon Line-Art", category: "motion_graphic", kind: "style", reliability: "medium", description: "Glowing outline graphics on dark backgrounds — sleek futuristic techy energy.", whenToUse: "Tech/crypto/gaming intros, dark-mode brand loops, futuristic accents.", keywords: "neon line art, glowing outline graphics, dark background, luminous gradient strokes, light bloom glow, synthwave palette, futuristic tech aesthetic, animated neon trails, sleek minimal motion" },

  // ── RETRO / ERA ──
  { id: "vhs_80s", name: "80s VHS / Analog Tape", category: "retro_era", kind: "style", reliability: "high", description: "Degraded magnetic-tape look with scanlines and color bleed — 80s home-recording nostalgia.", whenToUse: "Nostalgic, lo-fi, eerie or 'found footage' content, retro ads.", keywords: "VHS camcorder aesthetic, heavy analog grain, chromatic aberration, horizontal tracking lines, scanlines, color bleed, tape distortion, on-screen timestamp, low resolution, slight image warble" },
  { id: "vintage_70s_film", name: "70s Vintage Film", category: "retro_era", kind: "style", reliability: "high", description: "Warm faded Eastmancolor look, magenta-shifted and grainy — 70s cinema and aged home movies.", whenToUse: "Warm nostalgic intimate or documentary-feel content with a sun-faded mood.", keywords: "1970s Eastmancolor film, faded color, magenta-shifted tones, heavy film grain, soft contrast, warm amber cast, halation glow, 35mm, slightly washed-out highlights, vintage cinematography" },
  { id: "camcorder_90s", name: "90s Camcorder / Hi8", category: "retro_era", kind: "style", reliability: "high", description: "Better-than-VHS tape video with interlacing and date stamp — 90s family camcorder.", whenToUse: "90s nostalgia, candid handheld authenticity, 'shot on a camcorder' moments.", keywords: "Hi8 camcorder footage, 1990s home video, interlaced video, date stamp overlay, handheld auto-focus hunting, mild grain, slightly soft image, fluorescent color cast, consumer camcorder look" },
  { id: "super8_home_movie", name: "Super-8 Home Movie", category: "retro_era", kind: "style", reliability: "high", description: "Grainy small-gauge FILM with light leaks and flicker — dreamy 60s–70s home movies.", whenToUse: "Warm dreamy nostalgic memory montages, emotional/romantic sequences.", keywords: "Super 8mm film, organic film grain, warm light leaks, soft dreamy colors, gate flicker, slight frame jitter, halation, faded vintage palette, sprocket-hole edge, handheld feel" },
  { id: "vaporwave", name: "Vaporwave", category: "retro_era", kind: "style", reliability: "medium", description: "Pastel ironic-nostalgic digital aesthetic of chrome, marble busts and 80s detritus.", whenToUse: "Surreal dreamy ironic nostalgic-internet content, retro-digital product art.", keywords: "vaporwave aesthetic, pastel pink and cyan palette, chrome reflections, Greek marble bust, retro 80s commercial elements, soft neon glow, dreamy surreal atmosphere, grid floor, glitchy nostalgia" },
  { id: "synthwave_retrofuture", name: "Synthwave / Retro-Future", category: "retro_era", kind: "style", reliability: "medium", description: "Bold 80s retro-future of neon grids, gradient sunsets and chrome — Outrun energy.", whenToUse: "Energetic bold nostalgic-futuristic content, titles, music-video energy.", keywords: "synthwave, retrowave, outrun aesthetic, neon pink cyan purple palette, glowing grid horizon, geometric sun, gradient sunset, chrome reflections, palm tree silhouettes, retro-future digital art" },
  { id: "sepia_antique", name: "Sepia / Antique", category: "retro_era", kind: "style", reliability: "high", description: "Monochrome brown-toned aged-print look — 19th/early-20th-century photographs.", whenToUse: "Historical, nostalgic, 'old photograph/letter' content, archival moods.", keywords: "sepia tone, antique photograph, aged brown monochrome, tintype look, faded edges, vignette, fine grain, soft focus, scratched emulsion, early 1900s photography" },
  { id: "technicolor_1950s", name: "1950s Technicolor", category: "retro_era", kind: "style", reliability: "medium", description: "Hyper-saturated glossy three-strip Technicolor — Golden-Age Hollywood musicals.", whenToUse: "Lush glamorous vibrant theatrical content with old-Hollywood polish.", keywords: "three-strip Technicolor, hyper-saturated bold color, glossy Golden-Age Hollywood, rich primary reds and blues, vibrant skin tones, glamorous studio lighting, lush saturated palette, painterly color depth" },

  // ── ARTISTIC MEDIUM (painterly = motion-fragile, mostly LOW/MEDIUM) ──
  { id: "oil_painting", name: "Oil Painting", category: "artistic_medium", kind: "style", reliability: "low", description: "Thick textured brushwork with luminous blended color — classical/expressive painting.", whenToUse: "Fine-art, fantasy, portrait or emotive content wanting a gallery-painting feel.", keywords: "oil painting, thick impasto brushstrokes, palette knife texture, visible canvas weave, rich luminous color depth, smooth blending, painterly highlights, glazed layers, fine-art portrait" },
  { id: "watercolor_wash", name: "Watercolor Wash", category: "artistic_medium", kind: "style", reliability: "low", description: "Translucent bleeding pigment washes on visible paper — soft delicate hand-painted art.", whenToUse: "Gentle dreamy light illustrative content — nature, children's-book, romantic moods.", keywords: "watercolor painting, loose wet-on-wet washes, pigment bleeding at edges, visible white paper highlights, granulated pigment, paper-grain texture, soft translucent color, delicate brush edges" },
  { id: "charcoal_sketch", name: "Charcoal / Pencil Sketch", category: "artistic_medium", kind: "style", reliability: "low", description: "Hand-drawn graphite/charcoal with visible strokes and paper texture — raw studio sketch.", whenToUse: "Moody raw intimate or concept-art content, monochrome 'drawn' reveals.", keywords: "charcoal sketch, graphite drawing, visible pencil strokes, smudged shading gradients, paper texture, black and white, erased highlights, sketchy hand-drawn energy, cross-hatching" },
  { id: "ink_woodblock", name: "Ink / Woodblock Print", category: "artistic_medium", kind: "style", reliability: "low", description: "Flat-color bold-contour ukiyo-e/ink look with limited palette — traditional Japanese print.", whenToUse: "Stylized graphic elegant or Eastern-art-inspired content with strong outlines.", keywords: "ukiyo-e woodblock print, flat color planes, decisive bold contours, limited palette, ink wash gradients, diluted black ink, visible woodgrain texture, graphic outlines, minimal detail" },
  { id: "pop_art", name: "Pop Art", category: "artistic_medium", kind: "style", reliability: "low", description: "Bold primary-color hard-edged comic look with Ben-Day dots — Warhol/Lichtenstein pop.", whenToUse: "Punchy energetic ironic advertising or youthful content with graphic impact.", keywords: "pop art style, Ben-Day dots, thick black outlines, bold primary color blocks, flat hard edges, comic strip aesthetic, Lichtenstein panel, Warhol silkscreen repetition, halftone print" },
  { id: "impressionist", name: "Impressionist", category: "artistic_medium", kind: "style", reliability: "low", description: "Visible broken brushstrokes capturing fleeting light and atmosphere — Monet-era painting.", whenToUse: "Atmospheric light-driven lyrical content — landscapes, gardens, soft emotional scenes.", keywords: "impressionist painting, visible broken brushstrokes, dappled light, soft atmospheric color, plein-air feel, loose dabs of paint, luminous palette, Monet-style, capturing fleeting light" },
  { id: "double_exposure", name: "Double Exposure", category: "artistic_medium", kind: "style", reliability: "low", description: "Two images blended into one silhouette-and-scene composite — poetic layered photography.", whenToUse: "Symbolic poetic identity-or-memory themes, striking title/portrait moments (keep motion minimal).", keywords: "double exposure, silhouette blended with landscape, overlapping translucent layers, two images merged, soft blend transitions, duotone base, fine grain, artistic photographic composite, negative space" },
  { id: "glitch_datamosh", name: "Glitch / Datamosh", category: "artistic_medium", kind: "style", reliability: "medium", description: "Digital-corruption aesthetic of pixel smears, datamoshing and tearing — broken-signal chaos.", whenToUse: "Edgy tech music-video or unsettling content and energetic transitions.", keywords: "glitch art, datamoshing, pixel sorting, RGB channel split, digital artifacts, screen tearing, compression blocks, scanline distortion, color smear, corrupted video signal" },

  // ── MOOD / GRADE MODIFIERS (layer onto a base style) ──
  { id: "mono_bw", name: "Monochrome B&W", category: "mood_grade", kind: "modifier", reliability: "high", description: "Full grayscale grade for timeless, dramatic or documentary weight.", whenToUse: "Emotional gravity, timelessness, emphasising form/contrast over color.", keywords: "black and white, monochrome, grayscale, rich tonal range, deep blacks, bright highlights, fine film grain, no color" },
  { id: "golden_warm", name: "Warm Golden Grade", category: "mood_grade", kind: "modifier", reliability: "high", description: "Warm amber/gold cast with soft backlight — sunset warmth and nostalgia.", whenToUse: "Cozy, romantic, hopeful or nostalgic warmth.", keywords: "warm golden hour grade, amber tones, soft warm backlight, honeyed highlights, long warm shadows, inviting glow" },
  { id: "cool_blue", name: "Cool Moody Blue Grade", category: "mood_grade", kind: "modifier", reliability: "high", description: "Cold blue/teal cast — night, isolation, tension or sleek modernity.", whenToUse: "Melancholy, mystery, cold tech, nighttime moods.", keywords: "cool blue grade, teal shadows, cold moonlight, desaturated blues, steel-grey tones, moody nighttime atmosphere, cyan highlights" },
  { id: "pastel_soft", name: "Pastel Soft", category: "mood_grade", kind: "modifier", reliability: "medium", description: "Low-contrast high-key pastel palette — gentle, dreamy, youthful softness.", whenToUse: "Light sweet whimsical or delicate moods (lifestyle, beauty, kids).", keywords: "pastel color palette, soft muted hues, high-key lighting, low contrast, gentle pink and mint tones, airy soft light, dreamy soft focus" },
  { id: "desaturated_muted", name: "Desaturated Muted", category: "mood_grade", kind: "modifier", reliability: "high", description: "Reduced-saturation grade for grounded realism, melancholy or period weight.", whenToUse: "Serious somber realistic or gritty/documentary tone.", keywords: "desaturated color, muted palette, bleach bypass look, reduced saturation, earthy tones, subtle contrast, grounded realistic grade" },
  { id: "vivid_saturated", name: "High-Saturation Vivid", category: "mood_grade", kind: "modifier", reliability: "high", description: "Punchy fully-saturated grade for energetic bold commercial impact.", whenToUse: "Vibrant joyful high-energy advertising-grade pop.", keywords: "high saturation, vivid bold color, punchy contrast, rich vibrant palette, deep saturated reds and blues, glossy commercial color" },
  { id: "dreamy_haze", name: "Dreamy Ethereal Haze", category: "mood_grade", kind: "modifier", reliability: "medium", description: "Soft diffusion, bloom and flares — ethereal romantic glow.", whenToUse: "Romantic surreal nostalgic or otherworldly softness.", keywords: "dreamy ethereal haze, soft diffusion glow, blooming highlights, gentle lens flare, atmospheric mist, soft focus, luminous halation, hazy light" },
];

const BY_ID = new Map(STYLE_LIBRARY.map((s) => [s.id, s]));
export const getStyle = (id: string): VisualStyle | undefined => BY_ID.get(id);
export const stylesByCategory = (c: StyleCategory): VisualStyle[] => STYLE_LIBRARY.filter((s) => s.category === c);
export const baseStyles = (): VisualStyle[] => STYLE_LIBRARY.filter((s) => s.kind === "style");
export const modifierStyles = (): VisualStyle[] => STYLE_LIBRARY.filter((s) => s.kind === "modifier");

/**
 * Map the reference B-roll classification (broll-style.ts taxonomy) → a candidate shortlist
 * + a sensible DEFAULT base style. Stage 1 of selection (narrow); an LLM can refine within
 * the shortlist using the descriptions.
 */
export const REF_CLASS_TO_STYLES: Record<string, { default: string; shortlist: string[] }> = {
  realistic_person: { default: "naturalistic_handheld", shortlist: ["naturalistic_handheld", "shallow_dof_portrait", "cinematic_film_look", "golden_hour_cinematic", "ugc_iphone_real", "documentary_verite"] },
  realistic_scene: { default: "cinematic_film_look", shortlist: ["cinematic_film_look", "wide_angle_environmental", "documentary_verite", "golden_hour_cinematic", "deakins_naturalistic"] },
  product: { default: "blender_product_3d", shortlist: ["blender_product_3d", "macro_detail", "high_key_bright", "low_key_moody"] },
  cartoon_animation: { default: "pixar_3d", shortlist: ["pixar_3d", "dreamworks_3d", "cel_shaded_anime", "studio_ghibli", "claymation_stopmotion"] },
  motion_graphics: { default: "flat_motion_graphics", shortlist: ["flat_motion_graphics", "isometric_infographic", "neon_line_art", "kinetic_typography"] },
  paper_explainer: { default: "paper_cutout_collage", shortlist: ["paper_cutout_collage", "whiteboard_doodle", "hand_drawn_sketch", "watercolor_2d"] },
};

/** A safe default base style when nothing matches. */
export const FALLBACK_STYLE = "cinematic_film_look";

/** Stage 1: the default base style for a reference classification. */
export function defaultStyleFor(refClass?: string): VisualStyle {
  const entry = refClass ? REF_CLASS_TO_STYLES[refClass] : undefined;
  return getStyle(entry?.default ?? FALLBACK_STYLE) ?? getStyle(FALLBACK_STYLE)!;
}

/** Stage 2 helper: build an LLM instruction that picks the best style from the shortlist. */
export function buildStyleSelectionInstruction(refClass: string | undefined, context: string): string {
  const ids = (refClass && REF_CLASS_TO_STYLES[refClass]?.shortlist) || baseStyles().slice(0, 8).map((s) => s.id);
  const list = ids.map((id) => getStyle(id)).filter(Boolean).map((s) => `- ${s!.id}: ${s!.description} (use when: ${s!.whenToUse}; reliability: ${s!.reliability})`).join("\n");
  return [
    `Pick the SINGLE best visual style for this video's B-roll. The reference's style class is "${refClass ?? "unknown"}".`,
    `Video context: ${context}`,
    `Candidates:`,
    list,
    `Prefer higher-reliability styles unless the context clearly calls for a stylized look.`,
    `Return ONLY JSON: {"styleId": "<one id from the list>", "reason": "<short>"}`,
  ].join("\n");
}

/** Compose the final style keyword fragment for a base (+ optional grade modifier). */
export function composeStyleKeywords(baseId: string, modifierId?: string): string {
  const base = getStyle(baseId);
  const mod = modifierId ? getStyle(modifierId) : undefined;
  const parts = [base?.keywords, mod?.kind === "modifier" ? mod.keywords : undefined].filter(Boolean);
  return parts.join(", ");
}
